name: Release
on:
    push:
        branches:
            - main
jobs:
    Release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm ci

            - name: Generate .env.production
              run: |
                  echo "REACT_APP_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env.production
                  echo "REACT_APP_OPEN_AI_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> .env.production

            - name: Generate build code
              run: npm run build --if-present

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
